# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beats < Formula
  desc "Structural clustering and code intelligence for Go repositories."
  homepage "https://github.com/somak2kai/beats"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somak2kai/beats/releases/download/v0.1.3/beats_0.1.3_darwin_amd64.tar.gz"
      sha256 "27e5a614134e523d965b16fa354879f2d6721137d99b5639d55affd3c58a5974"

      define_method(:install) do
        bin.install "beats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somak2kai/beats/releases/download/v0.1.3/beats_0.1.3_darwin_arm64.tar.gz"
      sha256 "31c1e2ccd624d66a36b936f199fbf85d5c2a05022c0fbf0a88cfdc83b27871dc"

      define_method(:install) do
        bin.install "beats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somak2kai/beats/releases/download/v0.1.3/beats_0.1.3_linux_amd64.tar.gz"
      sha256 "c374a23c0bf8838980e3e0311b7458d3bc126ed0258319212e488cb136707a03"
      define_method(:install) do
        bin.install "beats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somak2kai/beats/releases/download/v0.1.3/beats_0.1.3_linux_arm64.tar.gz"
      sha256 "55dcd0d4864fe5072a619b1096214c775afd19e0fcbb8e8170b1cbee506a04c9"
      define_method(:install) do
        bin.install "beats"
      end
    end
  end

  test do
    system "#{bin}/beats", "version"
  end
end
