# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beats < Formula
  desc "Structural clustering and code intelligence for Go repositories."
  homepage "https://github.com/somak2kai/beats"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somak2kai/beats/releases/download/v0.1.5/beats_0.1.5_darwin_amd64.tar.gz"
      sha256 "b99d84f38ee27c5a7f3ff90b095e5f87dc152b3fae4707831828086f2e228c18"

      define_method(:install) do
        bin.install "beats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somak2kai/beats/releases/download/v0.1.5/beats_0.1.5_darwin_arm64.tar.gz"
      sha256 "d2efc6c61e69696d52af0301d9518f5e965d5f0d2573a45b2fefe5aa8dcf3329"

      define_method(:install) do
        bin.install "beats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somak2kai/beats/releases/download/v0.1.5/beats_0.1.5_linux_amd64.tar.gz"
      sha256 "cd74dfd24e82ff12c3b467ddcfbaf69c4f082152d77ba3943e55e75ea82bae1e"
      define_method(:install) do
        bin.install "beats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somak2kai/beats/releases/download/v0.1.5/beats_0.1.5_linux_arm64.tar.gz"
      sha256 "214cab84578183b142daa3a156bb459b872a032411e8d8e8d397d24570e6310e"
      define_method(:install) do
        bin.install "beats"
      end
    end
  end

  test do
    system "#{bin}/beats", "version"
  end
end
